# Autogenerated wrapper script for OpenSSH_jll for x86_64-w64-mingw32
export scp, sftp, ssh, ssh_add, ssh_agent, ssh_keygen, ssh_keyscan

JLLWrappers.@generate_wrapper_header("OpenSSH")
JLLWrappers.@declare_executable_product(scp)
JLLWrappers.@declare_executable_product(sftp)
JLLWrappers.@declare_executable_product(ssh)
JLLWrappers.@declare_executable_product(ssh_add)
JLLWrappers.@declare_executable_product(ssh_agent)
JLLWrappers.@declare_executable_product(ssh_keygen)
JLLWrappers.@declare_executable_product(ssh_keyscan)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        scp,
        "bin\\scp.exe",
    )

    JLLWrappers.@init_executable_product(
        sftp,
        "bin\\sftp.exe",
    )

    JLLWrappers.@init_executable_product(
        ssh,
        "bin\\ssh.exe",
    )

    JLLWrappers.@init_executable_product(
        ssh_add,
        "bin\\ssh-add.exe",
    )

    JLLWrappers.@init_executable_product(
        ssh_agent,
        "bin\\ssh-agent.exe",
    )

    JLLWrappers.@init_executable_product(
        ssh_keygen,
        "bin\\ssh-keygen.exe",
    )

    JLLWrappers.@init_executable_product(
        ssh_keyscan,
        "bin\\ssh-keyscan.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
